# -*- coding: utf-8 -*-
"""1D PRW with time-varying control (trajectories).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jei--CILqCRHCkqIY8IwpMYlPxDi6ThM
"""

import numpy as np
import random
import matplotlib.pyplot as plt


N = 1   #Number of walkers
L = 100    #Total space
T = 100    #time steps
x_0 = L/2   #Initial position
dx = 1
a = .5


Vmatrix = np.zeros((T, N)) # velocity matrix
Xmatrix = np.zeros((T, N)) # position matrix

target_loc = L/4


def a(t):
  a = .91

  return a






def vinitial():   # chooses initial velocity
  r = random.random()
  if r > .5:
    return 1
  else:
    return -1







def v_t(prev_v, a): # determine new v
  r = random.uniform(0,1)
  if r < a:
    v = prev_v
  else:
    v = -prev_v

  return v




def x_pos():
    for n in range(N):
        x = x_0
        Xmatrix[0, n] = x # set initial position

        v = vinitial()
        Vmatrix[0, n] = v #initialize initial velocity

        for t in range(1, T):
            p_1 = a(t)



            v = v_t(Vmatrix[t-1,n], p_1) #assign velocities
            Vmatrix[t, n] = v

            step = v * dx

            x = x + step # position update


            if x >= L:  # periodic boundary conditions
                x -= L
            elif x < 0:
                x += L

            Xmatrix[t, n] = x # assign new positions
    return Xmatrix


Xmatrix = x_pos() # call function/fill matrix








fig, (plot1, plot2) = plt.subplots(1, 2, figsize=(15, 4)) # subplots

#trajectory plots
for n in range(N):
    plot1.plot(Xmatrix[range(T), n])
plot1.set_xlabel("Time (t)")
plot1.set_ylabel("Position (x)")


#Histogram
t = T // 32
#t = T-1
pos_t = Xmatrix[t,:]
norm_pos_t = (Xmatrix[t,:])/L

plot2.hist(pos_t, bins=L,  range=(0, L), edgecolor='black', density = True)




fig, (plot3, plot4) = plt.subplots(1, 2, figsize=(15, 4)) # 2nd set of subplots


'''
# mean
mean = np.mean(Xmatrix, axis=1)

plot3.plot(range(T), mean, color='black', linewidth=2)
plot3.set_xlabel("Time (t)")
plot3.set_ylabel("Mean")
'''
### persistence as a funciton of time
alist = []
for t in range(T):
  alist.append(a(t))
plot3.plot(range(T), alist, color='black', linewidth=2)
plot3.set_xlabel("Time (t)")
plot3.set_ylabel("a(t)")
plot3.set_title("Persistence level")


# 2nd moment
scnd_moment = np.mean(Xmatrix**2, axis = 1)
plt.figure()
plt.xlabel("Time (t))")
plt.ylabel("2nd moment")
plt.plot(range(T), scnd_moment, color='black', linewidth=2)

#variance
'''
#var = np.var(Xmatrix, axis=1)
var = scnd_moment - mean**2
plot4.plot(range(T), var, color='black', linewidth=2)
plot4.set_xlabel("Time (t)")
plot4.set_ylabel("Variance")

#theoretical variance for normal walk (a = .5)
Tvar = []

for i in range(1,T):
  TheVar = dx**2 * i
  Tvar.append(TheVar)


plot4.plot(range(T-1), Tvar, color='red', linewidth=2)
'''

plt.show()

import numpy as np
import random
import matplotlib.pyplot as plt

L = 100
T = 100
x_0 = 50
t_0 = 0
dx = 1



x_list = []
def x_pos(t):

  x = x_0
  x_list.append(x)
  for i in range(t-1):
    random_num = random.randint(0,1)
    if random_num > 0.5:
      step = dx
    else:
      step = -dx

    x_pos = x + step

    if x_pos >= L:
      x_pos -= L
    elif x_pos < 0:
      x_pos += L

    x_list.append(x_pos)

    x = x_pos

  return x_pos

x_pos(T)
t_list = list(range(T))



plt.xlabel("Time (t)")
plt.ylabel("Position (x)")



plt.plot(t_list,x_list, color = 'blue', label = 'Simple Random Walk')








#trajectory plots

plt.plot(Xmatrix[range(T), n], color = 'green', label = 'Persistent Random Walk, (p1 = .9)')
plt.legend()
plt.show()