# -*- coding: utf-8 -*-
"""2D PRW MFPT stochastic p_1 optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-AMrF3nm1rKaFWrIeQXSrx839leRSu4J
"""

import numpy as np
import random
from scipy.optimize import minimize_scalar
import matplotlib.pyplot as plt



N = 10  #Number of walkers
L = 10   # Length of lattice
T = 999999   #time steps
dx = 1      #step space

coordinates = np.arange(L) # creates array from 0 to L
Y, X = np.meshgrid(coordinates, coordinates) # creates 2D lattice grid L X L
pos_matrix = np.stack((X, Y), axis=-1) # L y columns, L x rows


target_loc = pos_matrix[2,2] # choose target location




# transformation matrices
a_matrix = np.array([[1,0],[0,1]]) # forward
b_matrix = np.array([[-1,0],[0,-1]]) # backward
c_matrix = np.array([[0,-1],[1,0]]) # left
d_matrix = np.array([[0,1],[-1,0]]) # right

# random vinitial function

def vinitial(i):   # chooses initial velocity
  r = random.choice([[0,1],[0,-1],[1,0],[-1,0]])
  return r

'''
#possible tejedor vinitial function?
def vinitial(i):
  if (i) % 4 == 0:
    return np.array([1,0])
  elif (i) % 4 == 1:
    return np.array([-1,0])
  elif (i) % 4 == 2:
    return np.array([0,1])
  else:
    return np.array([0,-1])
'''

# version 3 (tejedor)
def v_t(prev_v, p_1):
    r = random.random()
    p_2 = (1 - p_1)/3
    p_3 = p_2

    if r < p_1:
      R = a_matrix  # move forward
    elif r < p_1 + p_2:
      R = b_matrix  # move backward
    elif  r < p_1 + p_2 + p_3:
      R = c_matrix  # turn left
    else:
      R = d_matrix  # turn right

    v = R @ np.array(prev_v)
    return v


# position update function
def x_pos(pos_i, p):


    Xmatrix = np.zeros((T, N, 2))  # (x, y) position matrix
    Vmatrix = np.zeros((T, N, 2))  # (vx, vy) velocity matrix
    fpt = np.zeros(N) # intitialize first passage times array
    for n in range(N):
        x = np.array(pos_i)
        Xmatrix[0, n] = x # set initial position

        v = np.array(vinitial(n))
        Vmatrix[0, n] = v #initialize initial velocity

        for t in range(1, T):

            v = np.array(v_t(Vmatrix[t-1,n], p)) #assign velocities
            Vmatrix[t, n] = v

            step = v * dx

            x = x + step # position update
            x = x % L # boundary condition

            Xmatrix[t, n] = x # assign new positions






            if np.array_equal(Xmatrix[t,n], target_loc): # check to see if walker has hit target
                fpt[n] = t # fill array with first passage times
                break # stop the random walk
        else:
          fpt[n] = T
    return fpt


# run trajectories over all starting positions

 # initialize list for all FPTs
def mfpt(p1):
  all_fpt = []
  for i in range(L): #x
    for j in range(L): #y
        start_pos = pos_matrix[i, j]
        if np.array_equal(start_pos, target_loc):
            all_fpt.append(L**2)
            continue



        fpt = x_pos(start_pos, p1) # calculate FPTs and fill array for each position



        all_fpt.extend(fpt) # add all the FPTs to all_fpt list
  if len(all_fpt) == 0:
        return T

  mfpt = np.mean(all_fpt)

  return mfpt


result = minimize_scalar(mfpt, bounds=(0.1, .9), method='bounded')

print("optimal p1:", result.x)
print("minimum MFPT:", result.fun)



'''
MFPT = np.mean(all_fpt) #calculate mean first passage time over all positions and walkers
print(f"MFPT: {MFPT}")

print(f"{len(all_fpt)} out of {N * (L**2-1)} walkers found target")
'''
plt.show()