# -*- coding: utf-8 -*-
"""Fixed state vector optimization problem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJP4y5lEVY0tq9dCtVOT-zhkcO8ipJTW
"""

import numpy as np
import random
import matplotlib.pyplot as plt
from scipy.optimize import minimize
import cvxpy as cp

L = 20       # choose number of elements in array
k_nz = 20    # number of non-zero elements in array
k_z = L - k_nz

#n = 2   # number of elements in control vector



initial_state = np.zeros(L)
for l in range(k_nz):
  #initial_state[l] = random.random()
  initial_state[l] = 1

print("initial state:",initial_state)

target_state = np.ones(L) / L    # initialize target state array


a = cp.Variable()    # initialize cvxpy optimization variable




objective = cp.Minimize(cp.sum_squares(a * initial_state - target_state))   #cost function

constraints = [] # initialize constraints list

constraints.append(cp.sum(a * initial_state) == 1) # normalization constraint

constraints.append(a >= 0)
constraints.append(a <= 1)    # probabilty constraints



prob = cp.Problem(objective, constraints)   # set up problem for cvxpy to solve
prob.solve()



print("optimized scalar value:", a.value)
print("cost:", prob.value)
print("normalization:", np.sum((a.value * initial_state)))
print(prob.solver_stats.solver_name)


c_theory=1.0/k_nz-1.0/L

print("theory cost:", c_theory)

plt.show()