# -*- coding: utf-8 -*-
"""optimal p1(t) by updating state distribution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ul4tTdskpJFss9XELwCfKqzjelElsT6R
"""

import numpy as np
import random
from scipy.optimize import minimize
import matplotlib.pyplot as plt
import math as m

from scipy.sparse import lil_matrix
from scipy.sparse import identity
from scipy.sparse.linalg import spsolve
from scipy.sparse import lil_matrix, csr_matrix, vstack, hstack, identity
from scipy.sparse.linalg import norm
L = 7
T_max = 15000
coordinates = np.arange(L) # creates array from 0 to L
Y, X = np.meshgrid(coordinates, coordinates) # creates 2D lattice grid L X L
pos_matrix = np.stack((X, Y), axis=-1) # L y columns, L x rows


target_loc = pos_matrix[L // 2,L // 2]

# Create transition matrix functions

def coord_to_index(i,j,k):
  M = L**2
  if k == 0:
    return j + i * L
  elif k == 1:
    return j + i * L + M
  elif k == 2:
    return j + i * L + 2 * M
  else:
    return j + i * L + 3 * M


def k_prime(k, l):
  if l == 0:
    return k
  elif l == 1:
    if k == 0:
      return 1
    elif k == 1:
      return 0
    elif k == 2:
      return 3
    else:
      return 2

  elif l == 2:
    if k ==0:
      return 2
    elif k == 1:
      return 3
    elif k == 2:
      return 1
    else:
      return 0

  elif l == 3:
    if k == 0:
      return 3
    elif k == 1:
      return 2
    elif k == 2:
      return 0
    else:
      return 1

def create_M_matrix(p1, p2, p3, p4):
    M_matrix = lil_matrix((L**2 * 4, L**2 * 4))
    probs = [p1, p2, p3, p4]
    direction_vectors = {
        0: (0, 1),   #dj = +1
        1: (0, -1),  #dj = -1
        2: (1, 0),   #di = +1
        3: (-1, 0)   #di = -1
    }
    for i in range(L):
        for j in range(L):
            for k in range(4):
                index = coord_to_index(i, j, k)   # find initial index

                #if [i, j] == target_loc:
                if [i, j] == list(target_loc):  # zero out target loc rows
                   continue
                for l in range(4):
                  prob = probs[l]       #choose probability
                  new_k = k_prime(k,l)    #find new velocities
                  di, dj = direction_vectors[new_k]     # find new direction change
                  ni, nj = (i + di) % L, (j + dj) % L   # update position
                  next_index = coord_to_index(ni, nj, new_k)    #convert back to index
                  M_matrix[index, next_index] = prob     #fill matrix with prob to go from (i, j, k) to (i', j', k')



    return M_matrix.tocsr()


target_indices = []
for k in range(4):
  target_indices.append(coord_to_index(target_loc[0], target_loc[1], k))




def M_to_canonical_form(p1,p2,p3,p4):
  M = create_M_matrix(p1, p2, p3, p4)


  transient_indices = []
  for i in range(L**2 * 4):
    if i not in target_indices:
      transient_indices.append(i)   # find transient indices

  reordered_indices = transient_indices + target_indices
  M_reordered = M[reordered_indices, :][:, reordered_indices]

  t_len = len(transient_indices)
  a_len = len(target_indices)

  Q = M_reordered[:t_len, :t_len]
  R = M_reordered[:t_len, t_len:]


  zeros = lil_matrix((a_len, t_len))
  identity = np.identity(a_len)

  top = hstack([Q, R])
  bottom = hstack([zeros, identity])
  canonical = vstack([top, bottom])

  return canonical.tocsr()




def create_Q_matrix(p1, p2, p3, p4):
    M = create_M_matrix(p1, p2, p3, p4)
    #for k in range(4):
     # M[coord_to_index(target_loc[0], target_loc[1], k)] = 0

    transient_indices = []
    for i in range(L**2 * 4):
      if i not in target_indices:
         transient_indices.append(i)   # find transient indices

    reordered_indices = transient_indices + target_indices
    #print(reordered_indices)

    M_reordered = M[reordered_indices, :][:, reordered_indices]
    #print(M_reordered)

    t_len = len(transient_indices)
    a_len = len(target_indices)

    Q = M_reordered[:t_len, :t_len]
    R = M_reordered[:t_len, t_len:]


    zeros = lil_matrix((a_len, t_len))

    identity = np.identity(a_len)

    top = hstack([Q, R])
    bottom = hstack([zeros, identity])
    canonical = vstack([top, bottom])
    return Q.tocsr()


#Q = create_Q_matrix(0.25, 0.25, 0.25, 0.25)
#print(Q.shape)




mu_0 = np.ones(L**2 * 4)
for i in range(L**2 * 4):
  if i in target_indices:
    mu_0[i] = 0
  else:
    mu_0[i] = 1


mu_0 = mu_0 / np.sum(mu_0)



#mu_0 = np.zeros(L**2 * 4)
#mu_0[5] = 1




ta = T_max // 750   # set here how long each p1 interval should be



def find_time():
  p1_vals = np.linspace(0, 1, 500)
  M_matrices = {}
  for p1 in p1_vals:
    p2 = (1 - p1)/3
    M_matrices[p1] = create_M_matrix(p1, p2, p2, p2)


  p1_t = []
  mu_t = np.zeros((T_max, L**2 * 4))
  mu_t[0] = mu_0
  mfpt = 0

  for t in range(1,T_max):
    possible_mu_t = {}
    mu_t_sums = []
    for p1 in p1_vals:
      M = M_matrices[p1]
      mu_ttt = M @ mu_t[t - 1]
      possible_mu_t[p1] = mu_ttt

      mu_t_sum = np.sum(mu_ttt)
      mu_t_sums.append(mu_t_sum)

    mu_t_sum_idx= np.argmin(mu_t_sums)
    p1_t.append(p1_vals[mu_t_sum_idx])
    mu_t[t] = (possible_mu_t[p1_vals[mu_t_sum_idx]])

    if np.sum(mu_t[t]) <= .001:
      print("converged at t =", t)
      break

    print("sum of mu:", np.sum(mu_t[t]))
    sum_mu_t = np.sum(mu_t[t])
    mfpt += (sum_mu_t)

  meantime = mfpt

  return meantime, p1_t




time, opt_p1 = find_time()
print("mean time:", time)
print("optimal p1 values:", opt_p1)
plt.figure(figsize=(15, 5))
plt.plot(opt_p1)
plt.title(f"p1 over time for a {L} by {L} lattice")
plt.xlabel("time")
plt.ylabel("p1")


plt.show()

import numpy as np
import random
import matplotlib.pyplot as plt


##################################################### STOCHASTIC SIMULATION FOR best_p1 values
#T_max = new_T_max
N = 1000  #Number of walkers
dx = 1      #step space
T_max = 3000

def a(t):
  if t < 627:
    a = opt_p1[t]
  else:
    a = 0.6755610561056106
  return a




coordinates = np.arange(L) # creates array from 0 to L
Y, X = np.meshgrid(coordinates, coordinates) # creates 2D lattice grid L X L
pos_matrix = np.stack((X, Y), axis=-1) # L y columns, L x rows


target_loc = pos_matrix[L // 2,L // 2] # choose target location


Xmatrix = np.zeros((T_max, N, 2))  # (x, y) position matrix
Vmatrix = np.zeros((T_max, N, 2))  # (vx, vy) velocity matrix

# transformation matrices
a_matrix = np.array([[1,0],[0,1]]) # forward
b_matrix = np.array([[-1,0],[0,-1]]) # backward
c_matrix = np.array([[0,-1],[1,0]]) # left
d_matrix = np.array([[0,1],[-1,0]]) # right

# random vinitial function
'''
def vinitial(i):   # chooses initial velocity
  r = random.choice([[0,1],[0,-1],[1,0],[-1,0]])
  return r
'''

'''
#possible tejedor vinitial function?
def vinitial(i):
  if (i) % 4 == 0:
    return np.array([1,0])
  elif (i) % 4 == 1:
    return np.array([-1,0])
  elif (i) % 4 == 2:
    return np.array([0,1])
  else:
    return np.array([0,-1])
'''


# choose initial velocity
def vinitial(i):
  if i == 0:
    d = np.array([1,0]) # +x
  elif i == 1:
    d = np.array([-1,0]) # -x
  elif i == 2:
    d = np.array([0,1]) # +y
  elif i == 3:
    d = np.array([0,-1]) # -y
  return d





# velocity update version 3 (tejedor)
def v_t(prev_v, p_1):
    r = random.random()

    p_2 = (1 - p_1)/3
    p_3 = p_2



    if r < p_1:
      R = a_matrix  # move forward
    elif r < p_1 + p_2:
      R = b_matrix  # move backward
    elif  r < p_1 + p_2 + p_3:
      R = c_matrix  # turn left
    else:
      R = d_matrix  # turn right

    v = R @ np.array(prev_v)
    return v




# position update function
def x_pos(pos_i):
    fpt = np.zeros(N) # intitialize first passage times array
    for n in range(N):
        x = np.array(pos_i)
        Xmatrix[0, n] = x # set initial position

        v = np.array(vinitial(0))
        Vmatrix[0, n] = v #initialize initial velocity

        for t in range(1, T_max):

            p1 = a(t)

            v = np.array(v_t(Vmatrix[t-1,n], p1)) #assign velocities
            Vmatrix[t, n] = v

            step = v * dx

            x = x + step # position update
            x = x % L # boundary condition

            Xmatrix[t, n] = x # assign new positions

            if np.array_equal(Xmatrix[t,n], target_loc): # check to see if walker has hit target
                fpt[n] = t # fill array with first passage times
                break # stop the random walk

    return fpt








# run trajectories over all starting positions

mfpt_map = np.zeros([L, L])
all_fpt = []  # initialize list for all FPTs
fptpos = np.zeros([N, L, L])  # store FPTs for each walker at each initial position

for i in range(L):  # x
    for j in range(L):  # y
        start_pos = pos_matrix[i, j]

        if np.array_equal(start_pos, target_loc):  # skip target
            continue

        fpt = x_pos(start_pos)  # run walkers
        fpt = fpt[fpt > 0]  # remove zero (non-hits)

        all_fpt.extend(fpt)  # accumulate valid FPTs


        if len(fpt) == N:
          fptpos[:, i, j] = fpt
          mfpt_map[i,j] = np.mean(fpt)



fig, (plot1, plot2) = plt.subplots(1, 2, figsize=(15, 4)) # subplots



#trajectory plots

'''
for n in range(N):
    plot1.plot(Xmatrix[:, n, 0], Xmatrix[:, n, 1])
plot1.grid(True)
'''

MFPT = np.sum(all_fpt) / (L**2  * N) #calculate mean first passage time over all positions and walkers
'''
alist = []
for t in range(T_max):
  alist.append(a(t))
plot2.plot(range(T_max), alist)
'''

print(f"MFPT: {MFPT}")
print(f"{len(all_fpt)} out of {N * (L**2-1)} walkers found target")

'''
plot1.imshow(mfpt_map.T)
plot1.colorbar(label='MFPT')
plot1.scatter(*target_loc, color='red')
'''

plt.show()