# -*- coding: utf-8 -*-
"""plotting Q-opt mu dist and stochastic sim mu dist to compare.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13xQ9EWYp-PdofxUK6yp8LgJfg0oqF0od
"""

########################## OPTIMIZE Q

import numpy as np
import random
from scipy.optimize import minimize
import matplotlib.pyplot as plt
import math as m

from scipy.sparse import lil_matrix
from scipy.sparse import identity
from scipy.sparse.linalg import spsolve
from scipy.sparse import lil_matrix, csr_matrix, vstack, hstack, identity
from scipy.sparse.linalg import norm
L = 5
T_max = 250
coordinates = np.arange(L) # creates array from 0 to L
Y, X = np.meshgrid(coordinates, coordinates) # creates 2D lattice grid L X L
pos_matrix = np.stack((X, Y), axis=-1) # L y columns, L x rows


target_loc = pos_matrix[L // 2,L // 2]

# Create transition matrix functions

def coord_to_index(i,j,k):
  M = L**2
  if k == 0:
    return j + i * L
  elif k == 1:
    return j + i * L + M
  elif k == 2:
    return j + i * L + 2 * M
  else:
    return j + i * L + 3 * M


def k_prime(k, l):
  if l == 0:
    return k
  elif l == 1:
    if k == 0:
      return 1
    elif k == 1:
      return 0
    elif k == 2:
      return 3
    else:
      return 2

  elif l == 2:
    if k ==0:
      return 2
    elif k == 1:
      return 3
    elif k == 2:
      return 1
    else:
      return 0

  elif l == 3:
    if k == 0:
      return 3
    elif k == 1:
      return 2
    elif k == 2:
      return 0
    else:
      return 1

def create_M_matrix(p1, p2, p3, p4):
    M_matrix = lil_matrix((L**2 * 4, L**2 * 4))
    probs = [p1, p2, p3, p4]
    direction_vectors = {
        0: (0, 1),   #dj = +1
        1: (0, -1),  #dj = -1
        2: (1, 0),   #di = +1
        3: (-1, 0)   #di = -1
    }
    for i in range(L):
        for j in range(L):
            for k in range(4):
                index = coord_to_index(i, j, k)   # find initial index

                #if [i, j] == target_loc:
                if [i, j] == list(target_loc):  # zero out target loc rows
                   continue
                for l in range(4):
                  prob = probs[l]       #choose probability
                  new_k = k_prime(k,l)    #find new velocities
                  di, dj = direction_vectors[new_k]     # find new direction change
                  ni, nj = (i + di) % L, (j + dj) % L   # update position
                  next_index = coord_to_index(ni, nj, new_k)    #convert back to index
                  M_matrix[index, next_index] = prob     #fill matrix with prob to go from (i, j, k) to (i', j', k')



    return M_matrix.tocsr()


target_indices = []
for k in range(4):
  target_indices.append(coord_to_index(target_loc[0], target_loc[1], k))




def M_to_canonical_form(p1,p2,p3,p4):
  M = create_M_matrix(p1, p2, p3, p4)


  transient_indices = []
  for i in range(L**2 * 4):
    if i not in target_indices:
      transient_indices.append(i)   # find transient indices

  reordered_indices = transient_indices + target_indices
  M_reordered = M[reordered_indices, :][:, reordered_indices]

  t_len = len(transient_indices)
  a_len = len(target_indices)

  Q = M_reordered[:t_len, :t_len]
  R = M_reordered[:t_len, t_len:]


  zeros = lil_matrix((a_len, t_len))
  identity = np.identity(a_len)

  top = hstack([Q, R])
  bottom = hstack([zeros, identity])
  canonical = vstack([top, bottom])

  return canonical.tocsr()




def create_Q_matrix(p1, p2, p3, p4):
    M = create_M_matrix(p1, p2, p3, p4)
    #for k in range(4):
     # M[coord_to_index(target_loc[0], target_loc[1], k)] = 0

    transient_indices = []
    for i in range(L**2 * 4):
      if i not in target_indices:
         transient_indices.append(i)   # find transient indices

    reordered_indices = transient_indices + target_indices
    #print(reordered_indices)

    M_reordered = M[reordered_indices, :][:, reordered_indices]
    #print(M_reordered)

    t_len = len(transient_indices)
    a_len = len(target_indices)

    Q = M_reordered[:t_len, :t_len]
    R = M_reordered[:t_len, t_len:]


    zeros = lil_matrix((a_len, t_len))

    identity = np.identity(a_len)

    top = hstack([Q, R])
    bottom = hstack([zeros, identity])
    canonical = vstack([top, bottom])
    return Q.tocsr()


#Q = create_Q_matrix(0.25, 0.25, 0.25, 0.25)
#print(Q.shape)




mu_0 = np.ones(L**2 * 4 - 4)
mu_0 = mu_0 / np.sum(mu_0)


ta = T_max // 750   # set here how long each p1 interval should be



newT_max = 0
def find_time():
  selected_p1s = []

  p1_vals = np.linspace(0, 1, 400)
  Q_matrices = {}
  for p1 in p1_vals:
        p2 = (1 - p1) / 3
        Q = create_Q_matrix(p1, p2, p2, p2)
        Q_matrices[p1] = Q

  I = identity(L**2 * 4 - 4, format='csr')
  N = I.copy()

  qlist = []
  for i in range(len(p1_vals)):
    qlist.append(np.sum(Q_matrices[p1_vals[i]]))
    argmin = np.argmin(qlist)

  Q_power = Q_matrices[p1_vals[argmin]].copy()
  Q_power = Q_matrices[p1_vals[99]]

  mu_t = np.zeros((T_max, len(mu_0)))
  mu_t[0] = mu_0
  mu_t_sums = [np.sum(mu_0)]

  for t in range(1, T_max):
    N_prev = N.copy()
    N += Q_power

    possible_Q_power = []
    q_powers_sum = []


    for p1 in p1_vals:
      Q_next = Q_power @ Q_matrices[p1]
      possible_Q_power.append(Q_next)
      q_powers_sum.append(np.sum(Q_next))


    best_idx = np.argmin(q_powers_sum)
    Q_power = possible_Q_power[best_idx]

    mu_t[t] = Q_power @ mu_t[t-1]
    mu_t_sums.append(np.sum(mu_t[t]))

    best_p1 = p1_vals[best_idx]
    selected_p1s.append(best_p1)


    delta = abs(N.sum() - N_prev.sum())
    if delta <= 0.01:      # current form of checking convergence, could be improved possibly?
      print("max t:",t)
      newT_max = t
      break

  c = np.ones((L**2 * 4 - 4, 1))
  mfpt = N @ c
  meantime = np.sum(mfpt) / (L**2 * 4)


  integ_mu = np.sum(mu_t_sums)


  #return mfpt
  return meantime, selected_p1s, mu_t_sums, integ_mu

time, opt_p1, mutsums, integrated_mu = find_time()
'''
print("mean time:", time)
print("optimal p1 values:", opt_p1)
plt.figure(figsize=(15, 5))
plt.plot(opt_p1)
plt.title(f"p1 over time for a {L} by {L} lattice")
plt.xlabel("time")
plt.ylabel("p1")
'''



mu_0 = np.ones(L**2 * 4)
mu_0[target_indices] = 0
mu_0 = mu_0 / np.sum(mu_0)



def find_mass(p):
  p2 = (1 - p) / 3
  Q = create_Q_matrix(p, p2, p2, p2)
  M = create_M_matrix(p, p2, p2, p2)
  mu_t = np.zeros((T_max+1, L**2 * 4))
  mu_t[0] = mu_0
  mu_sums = []
  mu_sums.append(np.sum(mu_0))


  for t in range(T_max - 1):
    mu_ttt = M @ mu_t[t]
    mu_t[t+1] = mu_ttt

    mu_sum = np.sum(mu_ttt)

    mu_sums.append(mu_sum)
  mu_integral = np.sum(mu_sums)

  return mu_sums, mu_integral


#mus , mu_int= find_mass((0.47967390338107563))

#simple_rw_mus, mu_srw_int = find_mass(0.25)



#print("mu optimal p1 integrated:", mu_int)
#print("mu simple rw integrated:", mu_srw_int)

print("integrated mu for Q-optimized p1(t)", integrated_mu)




plt.figure(figsize=(8, 5))
plt.plot(mutsums, label = 'Q-Optimization p1(t)' )
plt.title(f"probability in transient states over time")
plt.xlabel("time")
plt.ylabel("Probabilities")



#plt.plot(mus, label = 'Optimal Static p1')


#plt.plot(simple_rw_mus, label = 'Simple RW')

#plt.plot(probmass, label = 'State-Dependent MDP (lower bound)')
plt.legend()








plt.show()

############################################################################################################################################################################################################
##########################################################################################################################################################################
##########################################################################################################################################################################
import numpy as np
import random
import matplotlib.pyplot as plt


##################################################### STOCHASTIC SIMULATION FOR best_p1 values

N = 500  #Number of walkers
L = 5   # Length of lattice
T = 205   #time steps
dx = 1      #step space
#p_1 = .25    # prob to go forwards
#p_2 = .25    # prob to go backwards
#p_3 = .25    # prob to turn left
#p_4 = .25    # prob to turn right

n_max = T // 4

def a(t):
  if t < len(opt_p1):
    a = opt_p1[t]
  else:
    a = 0.6756479531224381

  return a




coordinates = np.arange(L) # creates array from 0 to L
Y, X = np.meshgrid(coordinates, coordinates) # creates 2D lattice grid L X L
pos_matrix = np.stack((X, Y), axis=-1) # L y columns, L x rows


target_loc = pos_matrix[L // 2,L // 2] # choose target location


Xmatrix = np.zeros((T, N, 2))  # (x, y) position matrix
Vmatrix = np.zeros((T, N, 2))  # (vx, vy) velocity matrix

# transformation matrices
a_matrix = np.array([[1,0],[0,1]]) # forward
b_matrix = np.array([[-1,0],[0,-1]]) # backward
c_matrix = np.array([[0,-1],[1,0]]) # left
d_matrix = np.array([[0,1],[-1,0]]) # right

# random vinitial function
'''
def vinitial(i):   # chooses initial velocity
  r = random.choice([[0,1],[0,-1],[1,0],[-1,0]])
  return r
'''

'''
#possible tejedor vinitial function?
def vinitial(i):
  if (i) % 4 == 0:
    return np.array([1,0])
  elif (i) % 4 == 1:
    return np.array([-1,0])
  elif (i) % 4 == 2:
    return np.array([0,1])
  else:
    return np.array([0,-1])
'''


# choose initial velocity
def vinitial(i):
  if i == 0:
    d = np.array([1,0]) # +x
  elif i == 1:
    d = np.array([-1,0]) # -x
  elif i == 2:
    d = np.array([0,1]) # +y
  elif i == 3:
    d = np.array([0,-1]) # -y
  return d





# velocity update version 3 (tejedor)
def v_t(prev_v, p_1):
    r = random.random()

    p_2 = (1 - p_1)/3
    p_3 = p_2



    if r < p_1:
      R = a_matrix  # move forward
    elif r < p_1 + p_2:
      R = b_matrix  # move backward
    elif  r < p_1 + p_2 + p_3:
      R = c_matrix  # turn left
    else:
      R = d_matrix  # turn right

    v = R @ np.array(prev_v)
    return v




# position update function
def x_pos(pos_i):
    fpt = np.zeros(N) # intitialize first passage times array

    hit_target = np.zeros(N, dtype=bool)
    #avg_pos_per = np.zeros(T)
    for n in range(N):
        x = np.array(pos_i)
        Xmatrix[0, n] = x # set initial position

        v = np.array(vinitial(0))
        Vmatrix[0, n] = v #initialize initial velocity

        #avg_pos_per[0] = x
        for t in range(1, T):

            p1 = a(t)

            v = np.array(v_t(Vmatrix[t-1,n], p1)) #assign velocities
            Vmatrix[t, n] = v

            step = v * dx

            x = x + step # position update
            x = x % L # boundary condition

            Xmatrix[t, n] = x # assign new positions

            #avg_pos_per[t] = x
            if np.array_equal(Xmatrix[t,n], target_loc): # check to see if walker has hit target
                fpt[n] = t # fill array with first passage times
                hit_target[n] = True
                break # stop the random walk

    return fpt, hit_target








# run trajectories over all starting positions

mfpt_map = np.zeros([L, L])
all_fpt = []  # initialize list for all FPTs
fptpos = np.zeros([N, L, L])  # store FPTs for each walker at each initial position



transient_count = np.zeros(T)
hit_counter = 0  # total walkers that reached the target

for i in range(L):
    for j in range(L):
        start_pos = pos_matrix[i, j]
        if np.array_equal(start_pos, target_loc):
            continue

        fpt, hit_target = x_pos(start_pos)

        all_fpt.extend(fpt)

        for n in range(N):
            if hit_target[n]:
                hit_counter += 1

            t_hit = int(fpt[n]) if fpt[n] > 0 else T
            transient_count[:t_hit] += 1



total_walkers = N * (L**2 - 1)  # excluding the target
transient_frac = transient_count / total_walkers



MFPT = np.mean(all_fpt) #calculate mean first passage time over all positions and walkers


#print(f"MFPT: {MFPT}")
#print(f"{len(all_fpt)} out of {N * (L**2 - 4)} walkers found target")

print("MFPT:", MFPT)
print(f"{hit_counter} out of {total_walkers} walkers found target")











plt.figure(figsize=(8, 5))
plt.plot(transient_frac, label="Fraction of walkers in transient states")
plt.title("Fraction of walkers in transient states over time")
plt.xlabel("Time")
plt.ylabel("Fraction")



plt.plot(mutsums, label = 'Q-Optimization p1(t)' )








plt.legend()
plt.show()

plt.show()