# -*- coding: utf-8 -*-
"""PRW 2D Continuous.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Loz8i7hSXa7p70KPx5XJQqlG-WG4dtUy
"""

import numpy as np
import random
import matplotlib.pyplot as plt


N = 1000  #Number of walkers
L = 100   #Total space
T = 100    #time steps
x_0 = 50   #Initial position
dx = 1      #step space
a = .5      # persistence level (probability to go forward)


Xmatrix = np.zeros((T, N, 2))  # (x, y) position matrix
Vmatrix = np.zeros((T, N, 2))  # (vx, vy) velocity matrix



def vinitial():   # chooses initial velocity
  r = random.random()
  theta = r * 2 * np.pi
  v_i = np.array([np.cos(theta), np.sin(theta)])
  return v_i




def v_t(prev_v):      # velocity update function
  r = random.random()
  if r < a:
    return np.array(prev_v)
  else:
    theta = random.random() * 2 * np.pi

    return np.array([np.cos(theta), np.sin(theta)])








def x_pos():
    for n in range(N):
        x = np.array([x_0, x_0])
        Xmatrix[0, n] = x # set initial position

        v = np.array(vinitial())
        Vmatrix[0, n] = v #initialize initial velocity

        for t in range(1, T):

            v = np.array(v_t(Vmatrix[t-1,n])) #assign velocities
            Vmatrix[t, n] = v

            step = v * dx

            x = x + step # position update


            x = x % L # boundary condition

            Xmatrix[t, n] = x # assign new positions
    return Xmatrix


Xmatrix = x_pos() # call function/fill matrix

fig, (plot1, plot2) = plt.subplots(1, 2, figsize=(15, 4)) # subplots



#trajectory plots


for n in range(N):
    plot1.plot(Xmatrix[:, n, 0], Xmatrix[:, n, 1])
plot1.grid(True)




#Histogram
t = 99
pos_t_x = Xmatrix[t,:,0]
pos_t_y = Xmatrix[t,:,1]
plot2.hist2d(pos_t_x,pos_t_y ,bins=25 , density = True)




fig, (plot3, plot4) = plt.subplots(1, 2, figsize=(15, 4)) # 2nd set of subplots
# mean
mean = np.mean(Xmatrix, axis=1)

plot3.plot(range(T), mean, color='black', linewidth=2)
plot3.set_xlabel("Time (t)")
plot3.set_ylabel("Mean")

# 2nd moment
scnd_moment = np.mean(Xmatrix**2, axis = 1)
plt.figure()
plt.xlabel("Time (t))")
plt.ylabel("2nd moment")
plt.plot(range(T), scnd_moment, color='black', linewidth=2)

#variance

#var = np.var(Xmatrix, axis=1)
var = scnd_moment - mean**2
plot4.plot(range(T), var, color='black', linewidth=2)
plot4.set_xlabel("Time (t)")
plot4.set_ylabel("Variance")

#theoretical variance for normal walk (a = .5)
Tvar = []

for i in range(1,T):
  TheVar = dx**2 * i
  Tvar.append(TheVar)


plot4.plot(range(T-1), Tvar, color='red', linewidth=2)



plt.show()