# -*- coding: utf-8 -*-
"""Stochastic simulation MFPTS with set p1(t) function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pt_81gv96aAIDmgWLIGPbr4Tt6PEBA5a
"""

import numpy as np
import random
import matplotlib.pyplot as plt


# STOCHASTIC SIMULATION FOR p1_t values

N = 50  #Number of walkers
L = 10   # Length of lattice
T = 5000   #time steps
dx = 1      #step space
#p_1 = .25    # prob to go forwards
#p_2 = .25    # prob to go backwards
#p_3 = .25    # prob to turn left
#p_4 = .25    # prob to turn right

n_max = T // 4

def p1_policy(t):
  p1_t = np.zeros(T)
  if t < (L/2)-1:
    p1_t[t] = 1
  else:

    if t % ((L/2)-1) <= 0:
      p1_t[t] = 0
    else:
      p1_t[t] = 1

  return p1_t[t]






def a(t):
  a = p1_policy(t)

  return a




coordinates = np.arange(L) # creates array from 0 to L
Y, X = np.meshgrid(coordinates, coordinates) # creates 2D lattice grid L X L
pos_matrix = np.stack((X, Y), axis=-1) # L y columns, L x rows


target_loc = pos_matrix[L // 2,L // 2] # choose target location


Xmatrix = np.zeros((T, N, 2))  # (x, y) position matrix
Vmatrix = np.zeros((T, N, 2))  # (vx, vy) velocity matrix

# transformation matrices
a_matrix = np.array([[1,0],[0,1]]) # forward
b_matrix = np.array([[-1,0],[0,-1]]) # backward
c_matrix = np.array([[0,-1],[1,0]]) # left
d_matrix = np.array([[0,1],[-1,0]]) # right

# random vinitial function
'''
def vinitial(i):   # chooses initial velocity
  r = random.choice([[0,1],[0,-1],[1,0],[-1,0]])
  return r
'''

'''
#possible tejedor vinitial function?
def vinitial(i):
  if (i) % 4 == 0:
    return np.array([1,0])
  elif (i) % 4 == 1:
    return np.array([-1,0])
  elif (i) % 4 == 2:
    return np.array([0,1])
  else:
    return np.array([0,-1])
'''


# choose initial velocity
def vinitial(i):
  if i == 0:
    d = np.array([1,0]) # +x
  elif i == 1:
    d = np.array([-1,0]) # -x
  elif i == 2:
    d = np.array([0,1]) # +y
  elif i == 3:
    d = np.array([0,-1]) # -y
  return d





# velocity update version 3 (tejedor)
def v_t(prev_v, p_1):
    r = random.random()

    p_2 = (1 - p_1)/3
    p_3 = p_2



    if r < p_1:
      R = a_matrix  # move forward
    elif r < p_1 + p_2:
      R = b_matrix  # move backward
    elif  r < p_1 + p_2 + p_3:
      R = c_matrix  # turn left
    else:
      R = d_matrix  # turn right

    v = R @ np.array(prev_v)
    return v




# position update function
def x_pos(pos_i):
    fpt = np.zeros(N) # intitialize first passage times array
    for n in range(N):
        x = np.array(pos_i)
        Xmatrix[0, n] = x # set initial position

        v = np.array(vinitial(0))
        Vmatrix[0, n] = v #initialize initial velocity

        for t in range(1, T):

            p1 = a(t)

            v = np.array(v_t(Vmatrix[t-1,n], p1)) #assign velocities
            Vmatrix[t, n] = v

            step = v * dx

            x = x + step # position update
            x = x % L # boundary condition

            Xmatrix[t, n] = x # assign new positions

            if np.array_equal(Xmatrix[t,n], target_loc): # check to see if walker has hit target
                fpt[n] = t # fill array with first passage times
                break # stop the random walk

    return fpt








# run trajectories over all starting positions

mfpt_map = np.zeros([L, L])
all_fpt = []  # initialize list for all FPTs
fptpos = np.zeros([N, L, L])  # store FPTs for each walker at each initial position

for i in range(L):  # x
    for j in range(L):  # y
        start_pos = pos_matrix[i, j]

        if np.array_equal(start_pos, target_loc):  # skip target
            continue

        fpt = x_pos(start_pos)  # run walkers
        fpt = fpt[fpt > 0]  # remove zero (non-hits)

        all_fpt.extend(fpt)  # accumulate valid FPTs


        if len(fpt) == N:
          fptpos[:, i, j] = fpt
          mfpt_map[i,j] = np.mean(fpt)



fig, (plot1, plot2) = plt.subplots(1, 2, figsize=(15, 4)) # subplots



#trajectory plots

'''
for n in range(N):
    plot1.plot(Xmatrix[:, n, 0], Xmatrix[:, n, 1])
plot1.grid(True)
'''

MFPT = np.mean(all_fpt) #calculate mean first passage time over all positions and walkers

alist = []
for t in range(T):
  alist.append(a(t))
plot2.plot(range(T), alist, color = 'black', linewidth=2)


print(f"MFPT: {MFPT}")
print(f"{len(all_fpt)} out of {N * (L**2-1)} walkers found target")

'''
plt.figure(figsize=(6, 5))
plt.imshow( mfpt_map.T,  cmap='plasma')
plt.colorbar(label='MFPT')
plt.scatter(*target_loc, color='red')
'''

plt.show()

############################### Analytical tejedor computation of static optimal p1 for L

def create_q_matrix(L):
    q_matrix = np.zeros((L, L), dtype=object)
    for n in range(L):
        for m in range(L):
            q_matrix[n, m] = np.array([(2 * np.pi * n) / L, (2 * np.pi * m) / L])
    return q_matrix


def create_A_value(e, L):

  A =  -(e * (L**2 - 1))/(1 - e)
  return A


def create_B_value(e):
  B = (1 + e**2)/(1 - e**2)
  return B


def create_h_matrix(e, q):
    h_matrix = np.zeros((L, L))

    for n in range( L):
        for m in range( L):
            qn = q[n, m][0]
            qm = q[n, m][1]

            if n == 0 and m == 0:
                h_matrix[0, 0] = 0
                continue


            a = (((e - 1)**2) / 2) * (np.cos(qn) / (1 + e**2 - 2 * e * np.cos(qn)))
            b = (((e - 1)**2) / 2) * (np.cos(qm) / (1 + e**2 - 2 * e * np.cos(qm)))


            c = a + b

            h_matrix[n, m] = 1 / (1 - c)
    #print(h_matrix)


    return h_matrix



def Q_sum(e, L):
    q_matrix = create_q_matrix(L)
    h_matrix = create_h_matrix(e, q_matrix)


    sum = np.sum(h_matrix[0,1:L]) + np.sum(h_matrix[1:L, 0]) + np.sum(h_matrix[1:L, 1:L])

    return sum



def TIME(e, L):
    A = create_A_value(e, L)
    B = create_B_value(e)
    q_sum = Q_sum(e, L)
    return  A + B * q_sum

print("ANALYTICAL OPTIMIZATION")
######################################################################## ANALYTICAL OPTIMIZATION




e_params = np.linspace(0,.99,1000)
e_LIST = []
time_LIST = []

for e in e_params:
  times = TIME(e,L)
  time_LIST.append(times)
  e_LIST.append(e)


minimum_time = min(time_LIST)
minimum_index = time_LIST.index(minimum_time)
minimum_e = e_LIST[minimum_index]

print("L =", L)
print("optimal MFPT:", minimum_time)
print("optimal e:",minimum_e)
print("optimal p1:", (minimum_e*3 + 1)/4)




plt.show()